project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  title: "Homophony"
  google-analytics: G-C5FTH8QPGW
  twitter-card: true
  open-graph: true
  site-url: "https://homophony.quest"
  description: "Music and notes by Homophony"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - notes.qmd
    right:
      - icon: rss
        href: notes.xml
      - icon: mastodon
        href: https://fosstodon.org/@MattCrumpLab
      - icon: youtube
        href: https://www.youtube.com/channel/UCmzAb7gmWJBQ0zX3spqxrNQ
        aria-label: Youtube
      - icon: spotify
        href: https://open.spotify.com/artist/21uZHA1jqXKOdkQmxR7ZcE?si=M2xiVdJpQG6OXuPW7URveg
      - icon: apple
        href: https://music.apple.com/us/artist/homophony/1531902633
  page-footer:
    center:
      - text: "Brought to you by Homophony, 2023"
        href: about.qmd
      - text: "Published with Quarto"
        href: https://quarto.org
format:
  html:
    theme: cosmo
    css: css/styles.css
    toc: true
