project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  title: "Homophony"
  google-analytics: G-C5FTH8QPGW
  site-url: "https://homophony.quest"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right:
      - icon: mastodon
        href: https://fosstodon.org/@MattCrumpLab
      - icon: youtube
        href: https://www.youtube.com/channel/UCmzAb7gmWJBQ0zX3spqxrNQ
        aria-label: Youtube
  page-footer:
    center:
      - text: "Brought to you by Homophony, 2023"
        href: about.qmd
      - text: "Published with Quarto"
        href: https://quarto.org
format:
  html:
    theme: quartz
    css: css/styles.css
    toc: true
