---
title: "Wall of Notes?"
editor: visual
---

```{r}
#| echo: false
html_tag_audio <- function(file, type = c("wav")) {
  type <- match.arg(type)
  htmltools::tags$audio(
    controls = "",
    htmltools::tags$source(
      src = file,
      type = glue::glue("audio/{type}", type = type)
    )
  )
}

```

This could be a place where I make notes about music things. Not sure yet. We'll see.

# 12/23/23 Practice

Back into practicing the piano and working on my chops. It's been a little bit painful because I am so out of practice. Perhaps there is a new year's resolution here to practice more. But, what to practice?

My recent routine is working through the circle of fifths and reclaiming some basics.

1. Playing Maj7 chords anti-clockwise and then clockwise through the circle of fifths
2. Playing II-V-I through the circle of fifths
3. Playing V7-V7 through the circle of fifths
4. Playing I-VI-II-V through the circle of fifths. This is the same progression as in "Heart and Soul", a duet we'd play as kids. Currently, I'm asking the question whether I can play this song effortlessly (chords in the left hand, melody in the right) in a key as I go around the circle, and if the answer is yes, I shouldn't practice this key, and if the answer is no, then I should.

Starting to get some fluency back. I was never that diligent at practicing through all of the keys, and some of them need a lot of work. 

Ideally, I'd like to keep a little journal here of practice strategies, reporting on: what I'm doing, what I'm hoping to get out of it (or did get out of it), and other observations that could relate to musical connections and/or connections to the cognitive science of skill learning. 

# General set-up issues

-   so many

-   Can't get a really good sync with Ableton. Don't bother with any live processing from Ableton, unless it is playback only. Fiddle with the error compensation until the lag is gone.

    -   256 bits

    -   28 ms error compensation

-   Still getting some audio dropout sometimes, not sure why.

# Dolphin Dance

`r html_tag_audio("../music/new/DolphinDanceFull_render 2_01.mp3", type = "wav")`

Have been messing about with Herbie Hancock's "Dolphin Dance" on the piano for a while.

Had a clear day to try some mixer mimicking. Plan was to develop my own voicings for everything, but mix them similar to the Maiden Voyage recording...and then jam it.

What happened:

-   Recorded the Hancock version into Ableton
-   Located BPM
-   Voices
    -   Rhodes
    -   Moog matriarch bass lines
    -   MPC drums
    -   OB-6 horns
-   For each voice, play with the original record. Keep recording in a loop using Ableton comping lanes
-   Fix messes by sampling in comping lanes/ explore have fun with fixing the mess
-   Duplicate the head, then solo overtop for a bit
-   Mix it down.
-   Try some final mixing touches.
